import type { Stock } from "@/types/portfolio";

// real portfolio data from workbook — cmp/pe/earnings will be replaced by live fetch later
export const Portfolio: Stock[] = [

  // ── Financial Sector ──────────────────────────────────────────────
  {
    id: 1,
    particulars: "HDFC Bank",
    sector: "Financial",
    buyPrice: 1490,
    qty: 50,
    exchangeSymbol: "HDFCBANK",
    exchange: "NSE",
    currentPrice: 1700.15,
    pe: 18.69,
    latestEarnings: 91.02,
  },
  {
    id: 2,
    particulars: "Bajaj Finance",
    sector: "Financial",
    buyPrice: 6466,
    qty: 15,
    exchangeSymbol: "BAJFINANCE",
    exchange: "NSE",
    currentPrice: 8419.6,
    pe: 32.63,
    latestEarnings: 257.8,
  },
  {
    id: 3,
    particulars: "ICICI Bank",
    sector: "Financial",
    buyPrice: 780,
    qty: 84,
    exchangeSymbol: "ICICIBANK",
    exchange: "NSE",
    currentPrice: 1215.5,
    pe: 17.68,
    latestEarnings: 68.72,
  },
  {
    id: 4,
    particulars: "Bajaj Housing",
    sector: "Financial",
    buyPrice: 130,
    qty: 504,
    exchangeSymbol: "BAJAJHFL",
    exchange: "NSE",
    currentPrice: 112.85,
    pe: 85.72,
    latestEarnings: 2.53,
  },
  {
    id: 5,
    particulars: "Savani Financials",
    sector: "Financial",
    buyPrice: 24,
    qty: 1080,
    exchangeSymbol: "SAVANIFINL",
    exchange: "BSE",
    currentPrice: 14.86,
    pe: null,
    latestEarnings: null,
  },

  // ── Tech Sector ────────────────────────────────────────────────────
  {
    id: 6,
    particulars: "Affle India",
    sector: "Technology",
    buyPrice: 1151,
    qty: 50,
    exchangeSymbol: "AFFLE",
    exchange: "NSE",
    currentPrice: 1459.6,
    pe: 55.53,
    latestEarnings: 26.11,
  },
  {
    id: 7,
    particulars: "LTI Mindtree",
    sector: "Technology",
    buyPrice: 4775,
    qty: 16,
    exchangeSymbol: "LTIM",
    exchange: "NSE",
    currentPrice: 4793.8,
    pe: 34.69,
    latestEarnings: 145.92,
  },
  {
    id: 8,
    particulars: "KPIT Tech",
    sector: "Technology",
    buyPrice: 672,
    qty: 61,
    exchangeSymbol: "KPITTECH",
    exchange: "NSE",
    currentPrice: 1293.1,
    pe: 46.57,
    latestEarnings: 27.77,
  },
  {
    id: 9,
    particulars: "Tata Tech",
    sector: "Technology",
    buyPrice: 1072,
    qty: 63,
    exchangeSymbol: "TATATECH",
    exchange: "NSE",
    currentPrice: 662,
    pe: 41.68,
    latestEarnings: 15.88,
  },
  {
    id: 10,
    particulars: "BLS E-Services",
    sector: "Technology",
    buyPrice: 232,
    qty: 191,
    exchangeSymbol: "BLSE",
    exchange: "NSE",
    currentPrice: 152.9,
    pe: 26.3,
    latestEarnings: 5.8,
  },
  {
    id: 11,
    particulars: "Tanla Platforms",
    sector: "Technology",
    buyPrice: 1134,
    qty: 45,
    exchangeSymbol: "TANLA",
    exchange: "NSE",
    currentPrice: 449.5,
    pe: 11.64,
    latestEarnings: 39.48,
  },

  // ── Consumer ───────────────────────────────────────────────────────
  {
    id: 12,
    particulars: "Dmart",
    sector: "Consumer",
    buyPrice: 3777,
    qty: 27,
    exchangeSymbol: "DMART",
    exchange: "NSE",
    currentPrice: 3451.1,
    pe: 82.63,
    latestEarnings: 41.75,
  },
  {
    id: 13,
    particulars: "Tata Consumer",
    sector: "Consumer",
    buyPrice: 845,
    qty: 90,
    exchangeSymbol: "TATACONSUM",
    exchange: "NSE",
    currentPrice: 961.1,
    pe: 26.56,
    latestEarnings: 134.77,  // note: this looked high in sheet, keeping as-is
  },
  {
    id: 14,
    particulars: "Pidilite",
    sector: "Consumer",
    buyPrice: 2376,
    qty: 36,
    exchangeSymbol: "PIDILITIND",
    exchange: "NSE",
    currentPrice: 2730,
    pe: 71.13,
    latestEarnings: 38.36,
  },

  // ── Power ──────────────────────────────────────────────────────────
  {
    id: 15,
    particulars: "Tata Power",
    sector: "Power",
    buyPrice: 224,
    qty: 225,
    exchangeSymbol: "TATAPOWER",
    exchange: "NSE",
    currentPrice: 351,
    pe: 29.36,
    latestEarnings: 11.94,
  },
  {
    id: 16,
    particulars: "KPI Green",
    sector: "Power",
    buyPrice: 875,
    qty: 50,
    exchangeSymbol: "KPIGREEN",
    exchange: "NSE",
    currentPrice: 402.4,
    pe: 29.26,
    latestEarnings: 13.75,
  },
  {
    id: 17,
    particulars: "Suzlon Energy",
    sector: "Power",
    buyPrice: 44,
    qty: 450,
    exchangeSymbol: "SUZLON",
    exchange: "NSE",
    currentPrice: 51.36,
    pe: 61.25,
    latestEarnings: 0.84,
  },
  {
    id: 18,
    particulars: "Gensol Engineering",
    sector: "Power",
    buyPrice: 998,
    qty: 45,
    exchangeSymbol: "GENSOL",
    exchange: "NSE",
    currentPrice: 372.6,
    pe: 39.51,
    latestEarnings: 5.57,
  },

  // ── Pipe Sector ────────────────────────────────────────────────────
  {
    id: 19,
    particulars: "Hariom Pipes",
    sector: "Pipes",
    buyPrice: 580,
    qty: 60,
    exchangeSymbol: "HARIOMPIPE",
    exchange: "NSE",
    currentPrice: 355.75,
    pe: 17.98,
    latestEarnings: 19.78,
  },
  {
    id: 20,
    particulars: "Astral",
    sector: "Pipes",
    buyPrice: 1517,
    qty: 56,
    exchangeSymbol: "ASTRAL",
    exchange: "NSE",
    currentPrice: 1317.6,
    pe: 67.13,
    latestEarnings: 19.59,
  },
  {
    id: 21,
    particulars: "Polycab",
    sector: "Pipes",
    buyPrice: 2818,
    qty: 28,
    exchangeSymbol: "POLYCAB",
    exchange: "NSE",
    currentPrice: 5000,
    pe: 40.91,
    latestEarnings: 121.97,
  },

  // ── Others ─────────────────────────────────────────────────────────
  {
    id: 22,
    particulars: "Clean Science",
    sector: "Others",
    buyPrice: 1610,
    qty: 32,
    exchangeSymbol: "CLEANSCIEN",
    exchange: "NSE",
    currentPrice: 1237.45,
    pe: 50.37,
    latestEarnings: 24.52,
  },
  {
    id: 23,
    particulars: "Deepak Nitrite",
    sector: "Others",
    buyPrice: 2248,
    qty: 27,
    exchangeSymbol: "DEEPAKNTR",
    exchange: "NSE",
    currentPrice: 1927.9,
    pe: 41.86,
    latestEarnings: 37.26,
  },
  {
    id: 24,
    particulars: "Fine Organic",
    sector: "Others",
    buyPrice: 4284,
    qty: 16,
    exchangeSymbol: "FINEORG",
    exchange: "NSE",
    currentPrice: 3743,
    pe: 41.86,
    latestEarnings: 37.26,
  },
  {
    id: 25,
    particulars: "Gravita India",
    sector: "Others",
    buyPrice: 2037,
    qty: 8,
    exchangeSymbol: "GRAVITA",
    exchange: "NSE",
    currentPrice: 1614.2,
    pe: 41.86,
    latestEarnings: 37.26,
  },
  {
    id: 26,
    particulars: "SBI Life",
    sector: "Others",
    buyPrice: 1197,
    qty: 49,
    exchangeSymbol: "SBILIFE",
    exchange: "NSE",
    currentPrice: 1405.45,
    pe: null,   // marked #N/A in sheet
    latestEarnings: -5.82,
  },
];
